title: לא מדויק
email: gadial@gmail.com
description: >- 
  בלוג על מתמטיקה ומדעי המחשב
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gadial.net" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: לא-מדויק-163347110378474
facebook_linkname: "לא מדויק"
twitter:
  card: summary
permalink: /:year/:month/:day/:title/
timezone: UTC
disqus:
  shortname: "not-precise"
rss: "RSS"
post_images: /assets/img
environment: production

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/main/default-card.png

# Trackers
google_analytics: "UA-3924539-2"
statcounter:
  id: 5444342
  security: 4a89cbe4
  invisible: 1

# Build settings
markdown: kramdown
kramdown:
  parse_span_html: false
  parse_block_html: false
theme: minima
plugins:
  - jekyll-feed

collections:
  categories:
    output: true
  tags:
    output: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - docs
  - Notebooks
  - node_modules
  - raw_posts
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
